(Add) Model Factories and Base Tests
Attendize/Attendize pull request #996
Opened 2021-10-29 19:04 UTC by HDVinnie

- Note this PR adds generated model factories, generated HTTP tests for controllers, generated unit tests for form requests, generated tests for console commands and configured a basic testing environment. 
- These tests are marked as incomplete!
- This PR also updates dependencies so I could use PHP 8.

```
vendor/bin/phpunit -d memory_limit=1024M
PHPUnit 8.5.21 by Sebastian Bergmann and contributors.

IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII  63 / 127 ( 49%)
IIIIIIIIII.IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 126 / 127 ( 99%)
.                                                               127 / 127 (100%)

Time: 15.41 seconds, Memory: 58.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 127, Assertions: 6, Incomplete: 125.
```

2021-10-29 19:09 UTC, HDVinnie commented
@johannac @quentincaffeino please take a look.

2021-10-29 19:27 UTC, HDVinnie commented
Can we make this project php8 only?

2021-10-29 21:22 UTC, quentincaffeino commented
> Can we make this project php8 only?

@HDVinnie, why do you need to upgrade it?

Besides proving that it works (these tests would do that when they are done), most of people don't use php8 yet. For me it isn't a problem since I have completely custom stack and switching version is not a problem. I know some people use cheapest hosting solutions to host this project so it would be really nice to hear from them if their hosting provider already supports php8.

2021-10-30 01:05 UTC, travtaz997 commented
> > Can we make this project php8 only?
> 
> @HDVinnie, why do you need to upgrade it?
> 
> Besides proving that it works (these tests would do that when they are done), most of people don't use php8 yet. For me it isn't a problem since I have completely custom stack and switching version is not a problem. I know some people use cheapest hosting solutions to host this project so it would be really nice to hear from them if their hosting provider already supports php8.
> 
> **Edit:** here are stats of how many actually use php8: https://blog.packagist.com/php-versions-stats-2021-1-edition/
> 
> tldr: Only around 10%.
> 
> I want this number to grow but I'm afraid such change could also hurt community.

Lurker here ... Just wanted to pop in and say I have a web hosting reseller account at HostGator and have quite a few sub-accounts.  Our only PHP options right now are 7.3 and 7.4.

![image](https://user-images.githubusercontent.com/61254648/139514808-b1344e2f-6d00-44c9-9ccf-3454a1bace48.png)

2021-12-03 13:13 UTC, quentincaffeino commented on database/factories/EventImageFactory.php
> +        'image_path' => $faker->word,
This could be replaced with a blank data image and ids should be replaced with real ids

2021-12-03 13:25 UTC, quentincaffeino commented on database/factories/MyBaseModelFactory.php
> +$factory->define(App\Models\MyBaseModel::class, function (Faker $faker) {
I believe this is an abstract entity

2021-12-03 14:41 UTC, quentincaffeino commented
All of these factories already exist:

```
AccountFactory
AccountPaymentGatewayFactory
AttendeeFactory
CountryFactory
CurrencyFactory
DateFormatFactory
DateTimeFormatFactory
DiscountCodeFactory
EventAccessCodesFactory
EventFactory
EventImageFactory
EventStatsFactory
OrderFactory
OrderItemFactory
OrderStatusFactory
OrganiserFactory
PaymentGatewayFactory
TicketFactory
TicketStatusFactory
TimezoneFactory
UserFactory
```

2021-12-03 14:44 UTC, quentincaffeino requested changes
Factories that were generated for already existing classes need to be removed

2021-12-03 17:32 UTC, HDVinnie commented
> Duplicate generated factories need to be removed

No the new ones need to stay....the old ones need to be removed. 

TBH I am not sure I am going to waste time on this project. Theres only one maintainer who is clearly busy in life which is fine but there is many things in this project that need work and I don't see it happening anytime soon.

2021-12-03 17:52 UTC, quentincaffeino commented
Old ones can't be just removed because some of them contain important code. Will need to go through them manually then and figure out what is required.

> TBH I am not sure I am going to waste time on this project. Theres only one maintainer who is clearly busy in life which is fine but there is many things in this project that need work and I don't see it happening anytime soon.

I understand, thank you for your contribution.

When you decide to drop this project I guess you can convert this pr to draft for history. If decide to use your work as a base, I also have your branch downloaded. Since I need to do tests anyways I'll get to them eventually.

2022-05-01 08:02 UTC, justynpride commented
Wondering what the current thought on the prioritising of the creating of tests. Reviewing all of the comments on the existing pull requests, other than people time, a limitation appears to be the lack of testing built in to the current code. Should the priority of contributors not be to resolve this, so that it is easier for @johannac and others to test review and merge new features and bug fixes. I've not used it but read a lot about the benefit of Laravel Shift.

2024-03-09 22:27 UTC, closed without merging